// <auto-generated />
using System;
using HPTourist.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HPTourist.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260421124413_Practice_Employees_and_Patients")]
    partial class Practice_Employees_and_Patients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HPTourist.Data.Models.EHIC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EncryptedEHICNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdentificationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationId")
                        .IsUnique();

                    b.ToTable("EHICs");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PracticeId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Identification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedDocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("CountryCode", "EncryptedDocumentNumber")
                        .IsUnique();

                    b.ToTable("Identificatios");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EHICId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PracticeId")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredLanguageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EHICId");

                    b.HasIndex("PracticeId");

                    b.HasIndex("PreferredLanguageId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Practice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Practices");
                });

            modelBuilder.Entity("HPTourist.Models.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveSubstance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AtcCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PharmaceuticalForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PrescriptionRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("PrescriptionRequestId");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("HPTourist.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrescriptionRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("HPTourist.Models.PrescriptionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PrescriptionRequests");
                });

            modelBuilder.Entity("HPTourist.Data.Models.EHIC", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Identification", "Identification")
                        .WithOne("EHIC")
                        .HasForeignKey("HPTourist.Data.Models.EHIC", "IdentificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identification");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Employee", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Practice", "Practice")
                        .WithMany("Employees")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Identification", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Patient", "Patient")
                        .WithOne("Identification")
                        .HasForeignKey("HPTourist.Data.Models.Identification", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Patient", b =>
                {
                    b.HasOne("HPTourist.Data.Models.EHIC", "EHIC")
                        .WithMany()
                        .HasForeignKey("EHICId");

                    b.HasOne("HPTourist.Data.Models.Practice", "Practice")
                        .WithMany("Patients")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HPTourist.Data.Models.Language", "PreferredLanguage")
                        .WithMany()
                        .HasForeignKey("PreferredLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EHIC");

                    b.Navigation("Practice");

                    b.Navigation("PreferredLanguage");
                });

            modelBuilder.Entity("HPTourist.Models.Medicine", b =>
                {
                    b.HasOne("HPTourist.Models.Prescription", null)
                        .WithMany("Medicines")
                        .HasForeignKey("PrescriptionId");

                    b.HasOne("HPTourist.Models.PrescriptionRequest", null)
                        .WithMany("Medicines")
                        .HasForeignKey("PrescriptionRequestId");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Identification", b =>
                {
                    b.Navigation("EHIC");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Patient", b =>
                {
                    b.Navigation("Identification");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Practice", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("HPTourist.Models.Prescription", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("HPTourist.Models.PrescriptionRequest", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
