// <auto-generated />
using System;
using HPTourist.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HPTourist.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HPTourist.Data.Models.EHIC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedEHICNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdentificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EncryptedEHICNumber")
                        .IsUnique();

                    b.HasIndex("IdentificationId")
                        .IsUnique();

                    b.ToTable("EHICs");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Identification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedDocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_Identifications");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("CountryCode", "EncryptedDocumentNumber")
                        .IsUnique();

                    b.ToTable("Identificatios");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveSubstance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AtcCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PharmaceuticalForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PrescriptionRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("PrescriptionRequestId");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EHICId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreferredLanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EHICId");

                    b.HasIndex("PracticeId");

                    b.HasIndex("PreferredLanguageId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Practice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Practices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-1111-4111-8111-000000000001"),
                            Address = "Damrak 1, 1012 LG Amsterdam",
                            Name = "Huisartsenpraktijk Tourist Doctor Amsterdam"
                        });
                });

            modelBuilder.Entity("HPTourist.Data.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrescriptionRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrescriptionRequestId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("HPTourist.Data.Models.PrescriptionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PrescriptionRequests");
                });

            modelBuilder.Entity("HPTourist.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_OneOfPatientOrEmployee", "(\"PatientId\" IS NOT NULL) <> (\"EmployeeId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("HPTourist.Data.Models.EHIC", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Identification", "Identification")
                        .WithOne("EHIC")
                        .HasForeignKey("HPTourist.Data.Models.EHIC", "IdentificationId");

                    b.Navigation("Identification");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Employee", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Practice", "Practice")
                        .WithMany("Employees")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Identification", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Patient", "Patient")
                        .WithOne("Identification")
                        .HasForeignKey("HPTourist.Data.Models.Identification", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Medicine", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Prescription", null)
                        .WithMany("Medicines")
                        .HasForeignKey("PrescriptionId");

                    b.HasOne("HPTourist.Data.Models.PrescriptionRequest", null)
                        .WithMany("Medicines")
                        .HasForeignKey("PrescriptionRequestId");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Patient", b =>
                {
                    b.HasOne("HPTourist.Data.Models.EHIC", "EHIC")
                        .WithMany()
                        .HasForeignKey("EHICId");

                    b.HasOne("HPTourist.Data.Models.Practice", "Practice")
                        .WithMany("Patients")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HPTourist.Data.Models.Language", "PreferredLanguage")
                        .WithMany()
                        .HasForeignKey("PreferredLanguageId");

                    b.Navigation("EHIC");

                    b.Navigation("Practice");

                    b.Navigation("PreferredLanguage");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Prescription", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HPTourist.Data.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HPTourist.Data.Models.PrescriptionRequest", "PrescriptionRequest")
                        .WithMany()
                        .HasForeignKey("PrescriptionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Patient");

                    b.Navigation("PrescriptionRequest");
                });

            modelBuilder.Entity("HPTourist.Data.Models.PrescriptionRequest", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HPTourist.Data.Models.User", b =>
                {
                    b.HasOne("HPTourist.Data.Models.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("HPTourist.Data.Models.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HPTourist.Data.Models.Patient", "Patient")
                        .WithOne()
                        .HasForeignKey("HPTourist.Data.Models.User", "PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Identification", b =>
                {
                    b.Navigation("EHIC");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Patient", b =>
                {
                    b.Navigation("Identification");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Practice", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("HPTourist.Data.Models.Prescription", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("HPTourist.Data.Models.PrescriptionRequest", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
